environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"

install:
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisdk.msi'
  - msmpisdk.msi /passive

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" ^
               -D USE_SEQ=ON   ^
               -D USE_MPI=ON   ^
               -D USE_OMP=ON   ^
               -D USE_TBB=ON   ^
               -D USE_STD=ON   ^
               -D MPI_C_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -D MPI_C_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" ^
               -D MPI_CXX_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -D MPI_CXX_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" .. ^
               -A Win32
  - cmd: cmake --build .
  - cmd: cd ..
  - cmd: set OMP_NUM_THREADS=4
  - cmd: scripts/run.bat
  
