name: Build application

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-9
        sudo apt-get install cppcheck
        sudo apt-get install mpich libmpich-dev
        sudo apt-get install libomp-dev libtbb-dev
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install setuptools cpplint
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=OFF -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        make -j4
        cd ..
      env:
        CC: gcc-9
        CXX: g++-9
    - name: Run tests
      run: |
        export OMP_NUM_THREADS=4
        source scripts/run.sh
#  macos-clang-build:
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Setup environment
#      run: |
#        brew update-reset
#        brew unlink python@3.8
#        brew install open-mpi libomp tbb
#        brew install cppcheck
#        sudo python3 -m pip install --upgrade pip
#        sudo python3 -m pip install setuptools cpplint
#    - name: Update submodules
#      run: git submodule update --init --recursive
#    - name: Build
#      run: |
#        export LDFLAGS="$LDFLAGS -L$(brew --prefix libomp)/lib"
#        export CFLAGS="$CFLAGS -I$(brew --prefix libomp)/include -I$(brew --prefix tbb)/include"
#        export CXXFLAGS="$CXXFLAGS -I$(brew --prefix libomp)/include -I$(brew --prefix tbb)/include"
#        mkdir build
#        cd build
#        cmake -D USE_SEQ=ON -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=OFF -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
#        make -j4
#        cd ..
#    - name: Run tests
#      run: |
#        export OMP_NUM_THREADS=4
#        source scripts/run_mac.sh
